### ISSUE TITLE
without vtr3_python

### ISSUE THREAD

**Issue by LSu666** [lisusdaniil/mm_masking#1]
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:a-krawciw/vtr3_python.git' into submodule path '/home/lsr/lab/githubproject/mm_masking/external/vtr3_python' failed
Failed to clone 'external/vtr3_python' a second time, aborting

**Comment by lisusdaniil** [comment]
The vtr3_python submodule has now been updated to the public vtr3_pose_graph submodule. Please make sure to pull the latest codebase to compile.
